# Generated by Django 2.1.1 on 2018-12-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181218_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='site',
        ),
    ]
