# Generated by Django 2.1.1 on 2018-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacher_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='postalCode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='province',
            field=models.CharField(max_length=50),
        ),
    ]
