# Generated by Django 2.1.1 on 2018-12-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20181218_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
