# Generated by Django 2.1.1 on 2018-12-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='owner',
            field=models.BigIntegerField(db_column='owner_id'),
        ),
    ]
