# Generated by Django 2.1.1 on 2018-12-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_id', models.IntegerField()),
                ('employee', models.CharField(max_length=50)),
                ('class_month', models.IntegerField()),
                ('class_year', models.IntegerField()),
                ('showed_up', models.IntegerField()),
                ('no_show', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance',
                'db_table': 'attendance',
                'managed': False,
            },
        ),
    ]
