# Generated by Django 2.1.1 on 2018-09-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('isActive', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_created_by', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.School')),
                ('teacher', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='teachers.Teacher')),
            ],
            options={
                'db_table': 'schedule',
                'verbose_name_plural': 'Schedules',
                'verbose_name': 'Schedule',
            },
        ),
    ]
